version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.50
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      # - 5778:5778
      - 16686:16686
      - 4317:4317 # for opentelemetry grpc
      - 4318:4318 # for opentelemetry http
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
  gin-with-otel:
    image: gin-with-otel:latest
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    privileged: true
    depends_on: # wait for postgres and jaeger and redis to be ready before starting
      - jaeger
      - postgres
      - redis
  # user-exist-check:
  #   image: user-exist-check:latest
  #   ports:
  #     - 8000:8000
  #   environment:
  #     - POSTGRES_USER
  #     - POSTGRES_PASSWORD
  #     - POSTGRES_DB
  #     - AWS_ACCESS_KEY_ID
  #     - AWS_SECRET_ACCESS_KEY
  #   depends_on: # wait for postgres to be ready before starting
  #     - postgres
  postgres:
    image: postgres:16.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./postgres:/var/lib/postgresql/data
    privileged: true
  redis:
    image: "redis:7.2.1"
    ports:
      - "6379:6379"
    command: redis-server /etc/redis.conf
    volumes:
      - "./redis:/data"
      - "./redis.conf:/etc/redis.conf"