apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.example.com # <names.plural>.<group>
spec:
  group: example.com
  names:
    kind: Foo
    listKind: FooList
    plural: foos
    singular: foo
  scope: Namespaced # `Namespaced` or `Cluster`
  versions:
  - name: v1alpha1
    served: true # served via REST API
    storage: true # stored in etcd
    additionalPrinterColumns:
    - name: TestString
      type: string
      description: A test string
      jsonPath: .spec.testString
    - name: TestNum
      type: integer
      description: A test number
      jsonPath: .spec.testNum
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              testString:
                type: string
              testNum:
                type: integer
                minimum: 1
                maximum: 10